# Generated by Django 3.0.5 on 2020-05-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('deaths', models.IntegerField(null=True, verbose_name='Deaths')),
                ('cumulative_deaths', models.IntegerField(null=True, verbose_name='Cumulative deaths')),
                ('confirmed', models.IntegerField(null=True, verbose_name='Confirmed')),
                ('cumulative_confirmed', models.IntegerField(null=True, verbose_name='Cumulative confirmed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'db_table': 'statistic',
                'unique_together': {('country', 'date')},
            },
        ),
    ]
