# Generated by Django 3.0.5 on 2020-04-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('country_iso_code', models.TextField(unique=True)),
                ('region', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('deaths', models.IntegerField()),
                ('cumulative_deaths', models.IntegerField()),
                ('confirmed', models.IntegerField()),
                ('cumulative_confirmed', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Country')),
            ],
        ),
    ]
