# Generated by Django 3.0.5 on 2020-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_iso_code',
            new_name='alpha2',
        ),
        migrations.AddField(
            model_name='country',
            name='alpha3',
            field=models.TextField(default='???', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='english_name',
            field=models.TextField(default='???', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='full_name',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=models.TextField(default='???'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='location_precise',
            field=models.TextField(default='???'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.TextField(null=True),
        ),
    ]
