# Generated by Django 3.0.5 on 2020-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Name')),
                ('iso_alpha2', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ISO Alpha2')),
                ('region', models.CharField(max_length=10, null=True, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
            },
        ),
    ]
